# cspell:words asyncio pytest setuptools

[build-system]
requires = [ "setuptools >= 64" ]
build-backend = "setuptools.build_meta"

[project]
name = "automation-scripts"
version = "4.0.0+development"
description = "Automation scripts for the local project"
requires-python = ">= 3.9"

dependencies = [
    "bhamon-development-toolkit[python] == 4.0.0+development",
    "mockito ~= 1.5.0",
    "pytest-asyncio ~= 0.24.0",
]

[project.scripts]
automation = "automation_scripts.run_command:main"
