# cspell:words asyncio pyinstaller pylint pytest setuptools

[build-system]
requires = [ "setuptools >= 64" ]
build-backend = "setuptools.build_meta"

[project]
name = "bhamon-development-toolkit"
version = "4.0.0+development"
description = "Toolkit for automating software development tasks"
requires-python = ">= 3.9"

authors = [
    { name = "Benjamin Hamon", email = "development@benjaminhamon.com" }
]

maintainers = [
    { name = "Benjamin Hamon", email = "development@benjaminhamon.com" }
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

dependencies = []

[project.optional-dependencies]
all = [
    "pyinstaller ~= 6.10.0",
    "twine ~= 5.1.1",
]

python = [
    "pyinstaller ~= 6.10.0",
    "twine ~= 5.1.1",
]

dev = [
    "mockito ~= 1.5.0",
    "pylint ~= 3.2.6",
    "pytest ~= 8.3.2",
    "pytest-json ~= 0.4.0",
    "pytest-asyncio ~= 0.24.0",
]

[project.urls]
"Source" = "https://github.com/BenjaminHamon/DevelopmentToolkit"

[tool.setuptools]
license-files = [ "../../About.md", "../../License.txt" ]
